- name: Reset Kubernetes component
  shell: "kubeadm reset"
  register: reset_cluster

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join \
                 --token {{ token }} \
                 {{ controller_private_ip }}:6443 \
                 --discovery-token-unsafe-skip-ca-verification
  register: join_cluster

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: GlusterFS - load dm_* modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - dm_snapshot
    - dm_mirror
    - dm_thin_pool
  tags: glusterfs
  when: glusterfs is defined and glusterfs == "1"

- name: GlusterFS - install glusterfs-client package
  apt:
    name: glusterfs-client
    state: present
  tags: glusterfs
  when: glusterfs is defined and glusterfs == "1"
