- hosts: all
  become: yes
  roles: 
    - k8s-common
  tags:
    - common

- hosts: controller
  become: yes
  roles:
    - k8s-controller
  vars:
    # TODO : get generated token
    token: xgl5bs.4el4ta2mqs1jw2aa
  tags:
    - controller
  
- hosts: worker
  become: yes
  roles:
    - k8s-worker
  vars:
    # TODO : get generated token
    token: xgl5bs.4el4ta2mqs1jw2aa
  tags:
    - worker
