- hosts: all
  become: yes
  roles: 
    - k8s-common
  tags:
    - common

- hosts: controller
  become: yes
  roles:
    - k8s-controller
  tags:
    - controller
  
- hosts: worker
  become: yes
  roles:
    - k8s-worker
  tags:
    - worker
