- name: Kubeadm - Reset
  shell: "kubeadm reset"
  register: reset_cluster

- name: Kubeadm - Init
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --kubernetes-version v{{ kubernetes_version }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --apiserver-advertise-address {{ controller_private_ip }} \
                 --token {{ token }} \
                 {{ init_opts }}

- name: Kubeadm - Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Create .kube directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "/home/nicolas/.kube/"
    - "/root/.kube/"
  
- name: Copy admin.conf to Home directory
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  with_items:
    - "/home/nicolas/.kube/config"
    - "/root/.kube/config"

- name: Calico - Install
  shell: |
    kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
    kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
