- name: Reset Kubernetes component
  shell: "kubeadm reset"
  register: reset_cluster

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --kubernetes-version v{{ kubernetes_version }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --apiserver-advertise-address {{ controller_private_ip }} \
                 --token {{ token }} \
                 {{ init_opts }}

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
    
- name: Create .kube directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "/home/nicolas/.kube/"
    - "/root/.kube/"
    
  
- name: Copy admin.conf to Home directory
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  with_items:
    - "/home/nicolas/.kube/config"
    - "/root/.kube/config"

- name: install flannel
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
